//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_ConvUni_ConCliente.ConversionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credentials", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.modelo")]
    [System.SerializableAttribute()]
    public partial class Credentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConversionServiceReference.IConversion")]
    public interface IConversion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversion/Login", ReplyAction="http://tempuri.org/IConversion/LoginResponse")]
        bool Login(WS_ConvUni_ConCliente.ConversionServiceReference.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversion/Login", ReplyAction="http://tempuri.org/IConversion/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(WS_ConvUni_ConCliente.ConversionServiceReference.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversion/ConvertirCelsiusAFahrenheit", ReplyAction="http://tempuri.org/IConversion/ConvertirCelsiusAFahrenheitResponse")]
        double ConvertirCelsiusAFahrenheit(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversion/ConvertirCelsiusAFahrenheit", ReplyAction="http://tempuri.org/IConversion/ConvertirCelsiusAFahrenheitResponse")]
        System.Threading.Tasks.Task<double> ConvertirCelsiusAFahrenheitAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversion/ConvertirFahrenheitACelsius", ReplyAction="http://tempuri.org/IConversion/ConvertirFahrenheitACelsiusResponse")]
        double ConvertirFahrenheitACelsius(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversion/ConvertirFahrenheitACelsius", ReplyAction="http://tempuri.org/IConversion/ConvertirFahrenheitACelsiusResponse")]
        System.Threading.Tasks.Task<double> ConvertirFahrenheitACelsiusAsync(double fahrenheit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConversionChannel : WS_ConvUni_ConCliente.ConversionServiceReference.IConversion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConversionClient : System.ServiceModel.ClientBase<WS_ConvUni_ConCliente.ConversionServiceReference.IConversion>, WS_ConvUni_ConCliente.ConversionServiceReference.IConversion {
        
        public ConversionClient() {
        }
        
        public ConversionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConversionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(WS_ConvUni_ConCliente.ConversionServiceReference.Credentials credentials) {
            return base.Channel.Login(credentials);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(WS_ConvUni_ConCliente.ConversionServiceReference.Credentials credentials) {
            return base.Channel.LoginAsync(credentials);
        }
        
        public double ConvertirCelsiusAFahrenheit(double celsius) {
            return base.Channel.ConvertirCelsiusAFahrenheit(celsius);
        }
        
        public System.Threading.Tasks.Task<double> ConvertirCelsiusAFahrenheitAsync(double celsius) {
            return base.Channel.ConvertirCelsiusAFahrenheitAsync(celsius);
        }
        
        public double ConvertirFahrenheitACelsius(double fahrenheit) {
            return base.Channel.ConvertirFahrenheitACelsius(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> ConvertirFahrenheitACelsiusAsync(double fahrenheit) {
            return base.Channel.ConvertirFahrenheitACelsiusAsync(fahrenheit);
        }
    }
}
