//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConversionServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credentials", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.modelo")]
    public partial class Credentials : object
    {
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConversionServiceReference1.IConversion")]
    public interface IConversion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversion/Login", ReplyAction="http://tempuri.org/IConversion/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(ConversionServiceReference1.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversion/ConvertirCelsiusAFahrenheit", ReplyAction="http://tempuri.org/IConversion/ConvertirCelsiusAFahrenheitResponse")]
        System.Threading.Tasks.Task<double> ConvertirCelsiusAFahrenheitAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversion/ConvertirFahrenheitACelsius", ReplyAction="http://tempuri.org/IConversion/ConvertirFahrenheitACelsiusResponse")]
        System.Threading.Tasks.Task<double> ConvertirFahrenheitACelsiusAsync(double fahrenheit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IConversionChannel : ConversionServiceReference1.IConversion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ConversionClient : System.ServiceModel.ClientBase<ConversionServiceReference1.IConversion>, ConversionServiceReference1.IConversion
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConversionClient() : 
                base(ConversionClient.GetDefaultBinding(), ConversionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IConversion.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionClient(EndpointConfiguration endpointConfiguration) : 
                base(ConversionClient.GetBindingForEndpoint(endpointConfiguration), ConversionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConversionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConversionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(ConversionServiceReference1.Credentials credentials)
        {
            return base.Channel.LoginAsync(credentials);
        }
        
        public System.Threading.Tasks.Task<double> ConvertirCelsiusAFahrenheitAsync(double celsius)
        {
            return base.Channel.ConvertirCelsiusAFahrenheitAsync(celsius);
        }
        
        public System.Threading.Tasks.Task<double> ConvertirFahrenheitACelsiusAsync(double fahrenheit)
        {
            return base.Channel.ConvertirFahrenheitACelsiusAsync(fahrenheit);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConversion))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConversion))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50176/ec.edu.monster.controlador/Conversion.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConversionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IConversion);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConversionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IConversion);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IConversion,
        }
    }
}
