

package ec.edu.monster.convertionclient;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.3.3.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: D66AF282617D7256703FC8C79B671C10E55882BDBDD2F1B85551AFA94EE2CBD134FEC923F8BE0242192286A9E41768C2D17AAA3E8C7DAF3C21EC8B1E9EA5BAFA
//------------------------------------------------------------------------

public class GPTBinaryObject implements java.io.Serializable
{
    private byte[] _bytes = null;    
    private transient java.io.InputStream _stream = null;

    private String _contentType = null;

    public GPTBinaryObject(byte[] bytes) {
        _bytes = bytes;
    }

    public GPTBinaryObject(java.io.InputStream stream) {
        _stream = stream;
    }
    
    public Object getUnderlayingObject()
    {
        if (_bytes != null)
            return _bytes;
        else if (_stream != null)
            return _stream;
        else 
            return null;
    }
    
    public java.io.InputStream getStream()
    {
        return _stream;
    }
    
    public byte[] getBytes() {
        return _bytes;
    }

    public void setBytes(byte[] bytes) {
        this._bytes = bytes;
    }

    public String getContentType() {
        return _contentType;
    }

    public void setContentType(String contentType) {
        this._contentType = contentType;
    }
}