package ec.edu.monster.convertionclient;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.3.3.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: D66AF282617D7256703FC8C79B671C10E55882BDBDD2F1B85551AFA94EE2CBD134FEC923F8BE0242192286A9E41768C2D17AAA3E8C7DAF3C21EC8B1E9EA5BAFA
//------------------------------------------------------------------------


public  class GPTCredentials  implements GPTISerializableObject
{
    private transient org.w3c.dom.Element __source=null;
    
    public org.w3c.dom.Element getOriginalXmlSource()
    {
        return __source;
    }
    private String Password =null;
    private String Username =null;

    
    public String getPassword()
    {
        return this.Password;
    }
    
    public void setPassword(String value)
    {
        this.Password = value;     
    }
    
    public String getUsername()
    {
        return this.Username;
    }
    
    public void setUsername(String value)
    {
        this.Username = value;     
    }
    public GPTCredentials()
    {
    }
    
    @Override
    public void serialize(org.w3c.dom.Element __node, GPTRequestResultHandler __handler)
    {


        org.w3c.dom.Element __PasswordItemElement=__handler.writeElementWithType(Password,String.class, "Password", "http://schemas.datacontract.org/2004/07/ec.edu.monster.modelo", __node, true);
        if(__PasswordItemElement != null)
        {
            __PasswordItemElement.setTextContent(this.Password.toString());
        }

        org.w3c.dom.Element __UsernameItemElement=__handler.writeElementWithType(Username,String.class, "Username", "http://schemas.datacontract.org/2004/07/ec.edu.monster.modelo", __node, true);
        if(__UsernameItemElement != null)
        {
            __UsernameItemElement.setTextContent(this.Username.toString());
        }
    }
    
    @Override
    public void loadWithXml(org.w3c.dom.Element __node,GPTRequestResultHandler __handler)
    {
        __source=__node;
        for(int i=0;i< __node.getChildNodes().getLength();i++)
        {
            org.w3c.dom.Node __child=__node.getChildNodes().item(i);
            if(__child instanceof org.w3c.dom.Element)
            {
                if(!loadProperty((org.w3c.dom.Element)__child,__handler))
                {
                }
            }
        }
    }
    
    protected boolean loadProperty(org.w3c.dom.Element __node, GPTRequestResultHandler __handler)
    {
        if( __node.getLocalName().equals("Password"))
        {
            if( GPTHelper.isValue(__node, "Password"))
            {
                this.Password = __node.getTextContent();
            }
            return true;
        }
        if( __node.getLocalName().equals("Username"))
        {
            if( GPTHelper.isValue(__node, "Username"))
            {
                this.Username = __node.getTextContent();
            }
            return true;
        }
        return false;
    }
}
